max_width = 100
binop_separator = "Front"
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
comment_width = 100
format_code_in_doc_comments = true
ignore = ['target']
imports_indent = "Block"
indent_style = "Block"
merge_imports = true
merge_derives = true
newline_style = "Auto"
space_after_colon = true
space_before_colon = false
trailing_comma = "Vertical"
wrap_comments = true
hard_tabs = false
