name: Update Pallets

on:
  repository_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  create-pr:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Add wasm toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true
      - name: Update pallets and commit
        run: |
          cargo update -p pallet-account-linker
          cargo update -p pallet-offchain-worker

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commit-message: Update litentry-pallets dependencies
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: feature/patch-${{ github.event.client_payload.sha }}
          delete-branch: true
          title: '[AutoPR] Dependency update triggered by litentry-pallets change'
          body: |
            This PR updates [litentry-pallets][1] dependencies to the latest HEAD of ${{ github.event.client_payload.ref }}
            
            It is generated automatically by [this commit][2]

            [1]: https://github.com/litentry/litentry-pallets
            [2]: https://github.com/litentry/litentry-pallets/commit/${{ github.event.client_payload.sha }}
          labels: auto-gen-pr
          #assignees: h4n0
          reviewers: |
            h4n0 
            buildtrust
            chenzongxiong
            Satoshi-Kusumoto
            suinuj
          #team-reviewers: 
          draft: false

