name: Update Pallets

on:
  repository_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  create-pr:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Add wasm toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true
      - name: Update pallets and commit
        run: |
          cargo update -p pallet-account-linker
          cargo update -p pallet-offchain-worker

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update litentry-pallets dependencies
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: feature/patch-{{ payload.sha }}
          delete-branch: true
          title: '[AutoPR] Dependency update triggered by litentry-pallets change'
          body: |
            This PR is automatically generated by [this commit][1]

          [1]: https://github.com/litentry/litentry-pallets/commit/{{ payload.sha }}
          labels: |
            auto-gen-pr
            #assignees: peter-evans
            #reviewers: peter-evans
          team-reviewers: |
            owners
            maintainers
          milestone: 1
          draft: false

